/**:
  ros__parameters:
    num_wheels: 4
    device: enp1s0
    vlin_max: 0.5
    va_max: 0.25
    vlin_acc_max: 0.15
    vlin_dec_max: 0.5
    va_acc_max: 0.15
    va_dec_max: 0.5

    wheel_models:
      list: ["KD165"]
      KD165:
        diameter: 0.165
        width: 0.06
        casteroffset: 0.015
        wheeldistance: 0.184
        velocitylimit: 100.0
        currentlimit: 1.0
        standbycurrent: 0.1
        canPivot: true

    wheel0:
      model: KD165
      ethercat_number: 1
      x: 1.0325
      y: -0.2425
      a: 1.5708

    wheel1:
      model: KD165
      ethercat_number: 2
      x: 1.0325
      y: 0.2425
      a: -1.5708

    wheel2:
      model: KD165
      ethercat_number: 3
      x: -1.0325
      y: 0.2425
      a: -1.5708

    wheel3:
      model: KD165
      ethercat_number: 4
      x: -1.0325
      y: -0.2425
      a: 1.5708

platform_driver:
  ros__parameters:
    modules:
      list: ["platform_driver"]
      platform_driver:
        type: platform_driver
        controller: velocity_platform_controller

